/*
 *  Source machine generated by GadToolsBox V2.0b
 *  which is (c) Copyright 1991-1993 Jaba Development
 *
 *  GUI Designed by : Michael D. Bayne
 */

#define GetString( g )      ((( struct StringInfo * )g->SpecialInfo )->Buffer  )
#define GetNumber( g )      ((( struct StringInfo * )g->SpecialInfo )->LongInt )

#define GD_BT_HIDE                             0
#define GD_BT_QUIT                             1
#define GD_LV_BLANKERS                         2
#define GD_BT_PREFS                            3
#define GD_BT_INFO                             4
#define GD_BT_TOGGLE                           5

#define GDX_BT_HIDE                            0
#define GDX_BT_QUIT                            1
#define GDX_LV_BLANKERS                        2
#define GDX_BT_PREFS                           3
#define GDX_BT_INFO                            4
#define GDX_BT_TOGGLE                          5

#define Blanker_CNT 6

extern struct IntuitionBase *IntuitionBase;
extern struct Library       *GadToolsBase;

extern struct Screen        *Scr;
extern UBYTE                 *PubScreenName;
extern APTR                  VisualInfo;
extern struct Window        *BlankerWnd;
extern struct Gadget        *BlankerGList;
extern struct IntuiMessage   BlankerMsg;
extern struct Gadget        *BlankerGadgets[6];
extern UWORD                 BlankerLeft;
extern UWORD                 BlankerTop;
extern UWORD                 BlankerWidth;
extern UWORD                 BlankerHeight;
extern UBYTE                *BlankerWdt;
extern struct TextAttr      *Font, Attr;
extern UWORD                 FontX, FontY;
extern UWORD                 OffX, OffY;
extern struct TextFont      *BlankerFont;
extern struct GfxBase       *GfxBase;
extern UWORD                 BlankerGTypes[];
extern struct NewGadget      BlankerNGad[];
extern ULONG                 BlankerGTags[];

extern int BT_HIDEClicked( void );
extern int BT_QUITClicked( void );
extern int LV_BLANKERSClicked( void );
extern int BT_PREFSClicked( void );
extern int BT_INFOClicked( void );
extern int BT_TOGGLEClicked( void );

extern int SetupScreen( void );
extern void CloseDownScreen( void );
extern int HandleBlankerIDCMP( void );
extern int BlankerCloseWindow();
extern int BlankerVanillaKey();
extern int OpenBlankerWindow( void );
extern void CloseBlankerWindow( void );
